[05-Jul-24 13:21:27 - INFO] - bot - Bot Running..!

Created by 
https://t.me/Madflix_Bots
[05-Jul-24 13:21:27 - INFO] - bot - ▂▃▄▅▆▇█▓▒░ASV░▒▓█▇▆▅▄▃▂
[05-Jul-24 13:24:51 - INFO] - root - Stop signal received (SIGINT). Exiting...
[05-Jul-24 13:24:52 - INFO] - bot - Bot stopped.
[05-Jul-24 13:24:58 - INFO] - bot - Bot Running..!

Created by 
https://t.me/Madflix_Bots
[05-Jul-24 13:24:58 - INFO] - bot - ▂▃▄▅▆▇█▓▒░ASV░▒▓█▇▆▅▄▃▂
[05-Jul-24 13:30:03 - INFO] - root - Stop signal received (SIGINT). Exiting...
[05-Jul-24 13:30:06 - INFO] - root - Stop signal received (SIGINT). Exiting...
[05-Jul-24 13:30:06 - INFO] - root - Stop signal received (SIGINT). Exiting...
[05-Jul-24 13:30:06 - INFO] - root - Stop signal received (SIGINT). Exiting...
[05-Jul-24 13:30:07 - INFO] - root - Stop signal received (SIGINT). Exiting...
[05-Jul-24 13:30:20 - INFO] - bot - Bot Running..!

Created by 
https://t.me/DarkHumorHub_bot
[05-Jul-24 13:30:20 - INFO] - bot - ▂▃▄▅▆▇█▓▒░ASV░▒▓█▇▆▅▄▃▂
[05-Jul-24 13:33:25 - INFO] - root - Stop signal received (SIGINT). Exiting...
[05-Jul-24 13:33:48 - INFO] - bot - Bot Running..!

Created by 
https://t.me/Madflix_Bots
[05-Jul-24 13:33:48 - INFO] - bot - ▂▃▄▅▆▇█▓▒░ASV░▒▓█▇▆▅▄▃▂
[05-Jul-24 13:40:41 - WARNING] - pyrogram.session.session - [Bot] Waiting for 3 seconds before continuing (required by "messages.EditMessage")
[05-Jul-24 13:40:44 - WARNING] - pyrogram.session.session - [Bot] Waiting for 3 seconds before continuing (required by "messages.EditMessage")
[05-Jul-24 13:40:47 - INFO] - bot - Bot stopped.
[05-Jul-24 15:19:40 - INFO] - bot - Bot Running..!

Created by 
https://t.me/Madflix_Bots
[05-Jul-24 15:19:40 - INFO] - bot - ▂▃▄▅▆▇█▓▒░ASV░▒▓█▇▆▅▄▃▂
[05-Jul-24 15:51:44 - INFO] - root - Stop signal received (SIGINT). Exiting...
[05-Jul-24 15:51:44 - INFO] - bot - Bot stopped.
[05-Jul-24 16:20:42 - INFO] - bot - Bot Running..!

Created by 
@LeadModerator
[05-Jul-24 16:20:42 - INFO] - bot - ▂▃▄▅▆▇█▓▒░ASV░▒▓█▇▆▅▄▃▂
[05-Jul-24 16:23:57 - INFO] - root - Stop signal received (SIGINT). Exiting...
[05-Jul-24 16:23:57 - INFO] - bot - Bot stopped.
[05-Jul-24 16:30:24 - WARNING] - bot - Peer id invalid: -1002174448712
[05-Jul-24 16:30:24 - WARNING] - bot - Make Sure bot is Admin in DB Channel, and Double check the CHANNEL_ID Value, Current Value -1002174448712
[05-Jul-24 16:30:24 - INFO] - bot - 
Bot Stopped. Text me at @LeadModerator for support
[05-Jul-24 16:31:17 - INFO] - bot - Bot Running..!

Created by 
@LeadModerator
[05-Jul-24 16:31:17 - INFO] - bot - ▂▃▄▅▆▇█▓▒░ASV░▒▓█▇▆▅▄▃▂
[05-Jul-24 16:44:29 - INFO] - root - Stop signal received (SIGINT). Exiting...
[05-Jul-24 16:44:29 - INFO] - bot - Bot stopped.
[05-Jul-24 17:55:19 - INFO] - bot - Bot Running..!

Created by 
@LeadModerator
[05-Jul-24 17:55:19 - INFO] - bot - ▂▃▄▅▆▇█▓▒░ASV░▒▓█▇▆▅▄▃▂
[05-Jul-24 17:58:39 - INFO] - root - Stop signal received (SIGINT). Exiting...
[05-Jul-24 17:58:40 - INFO] - bot - Bot stopped.
[05-Jul-24 20:09:59 - INFO] - bot - Bot Running..!

Created by 
@LeadModerator
[05-Jul-24 20:09:59 - INFO] - bot - ▂▃▄▅▆▇█▓▒░ASV░▒▓█▇▆▅▄▃▂
[05-Jul-24 20:10:40 - ERROR] - pyrogram.dispatcher - SSL handshake failed: ac-vgg236u-shard-00-02.w3vti6x.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1002) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),SSL handshake failed: ac-vgg236u-shard-00-01.w3vti6x.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1002) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),SSL handshake failed: ac-vgg236u-shard-00-00.w3vti6x.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1002) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 668805be2b2e292692bb8e7a, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-vgg236u-shard-00-00.w3vti6x.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-vgg236u-shard-00-00.w3vti6x.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1002) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-vgg236u-shard-00-01.w3vti6x.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-vgg236u-shard-00-01.w3vti6x.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1002) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-vgg236u-shard-00-02.w3vti6x.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-vgg236u-shard-00-02.w3vti6x.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1002) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
Traceback (most recent call last):
  File "C:\Users\anmol\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\anmol\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "E:\File-Sharing-Bot\plugins\start.py", line 32, in start_command
    if not await present_user(id):
           ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\File-Sharing-Bot\database\database.py", line 23, in present_user
    found = user_data.find_one({'_id': user_id})
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anmol\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymongo\collection.py", line 1495, in find_one
    for result in cursor.limit(-1):
  File "C:\Users\anmol\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymongo\cursor.py", line 1243, in next
    if len(self.__data) or self._refresh():
                           ^^^^^^^^^^^^^^^
  File "C:\Users\anmol\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymongo\cursor.py", line 1160, in _refresh
    self.__send_message(q)
  File "C:\Users\anmol\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymongo\cursor.py", line 1039, in __send_message
    response = client._run_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anmol\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymongo\_csot.py", line 108, in csot_wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anmol\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymongo\mongo_client.py", line 1431, in _run_operation
    return self._retryable_read(
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anmol\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymongo\mongo_client.py", line 1540, in _retryable_read
    return self._retry_internal(
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anmol\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymongo\_csot.py", line 108, in csot_wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anmol\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymongo\mongo_client.py", line 1507, in _retry_internal
    ).run()
      ^^^^^
  File "C:\Users\anmol\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymongo\mongo_client.py", line 2353, in run
    return self._read() if self._is_read else self._write()
           ^^^^^^^^^^^^
  File "C:\Users\anmol\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymongo\mongo_client.py", line 2483, in _read
    self._server = self._get_server()
                   ^^^^^^^^^^^^^^^^^^
  File "C:\Users\anmol\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymongo\mongo_client.py", line 2439, in _get_server
    return self._client._select_server(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anmol\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymongo\mongo_client.py", line 1322, in _select_server
    server = topology.select_server(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anmol\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymongo\topology.py", line 368, in select_server
    server = self._select_server(
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anmol\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymongo\topology.py", line 346, in _select_server
    servers = self.select_servers(
              ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anmol\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymongo\topology.py", line 253, in select_servers
    server_descriptions = self._select_servers_loop(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anmol\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymongo\topology.py", line 303, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: SSL handshake failed: ac-vgg236u-shard-00-02.w3vti6x.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1002) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),SSL handshake failed: ac-vgg236u-shard-00-01.w3vti6x.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1002) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),SSL handshake failed: ac-vgg236u-shard-00-00.w3vti6x.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1002) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 668805be2b2e292692bb8e7a, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-vgg236u-shard-00-00.w3vti6x.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-vgg236u-shard-00-00.w3vti6x.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1002) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-vgg236u-shard-00-01.w3vti6x.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-vgg236u-shard-00-01.w3vti6x.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1002) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-vgg236u-shard-00-02.w3vti6x.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-vgg236u-shard-00-02.w3vti6x.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1002) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
[05-Jul-24 20:24:42 - INFO] - bot - Bot Running..!

Created by 
@LeadModerator
[05-Jul-24 20:24:42 - INFO] - bot - ▂▃▄▅▆▇█▓▒░ASV░▒▓█▇▆▅▄▃▂
[05-Jul-24 20:24:54 - INFO] - root - Stop signal received (SIGINT). Exiting...
[05-Jul-24 20:24:54 - INFO] - bot - Bot stopped.
